name: PayDay
version: 1.5
main: de.brightstorm.payday
soft-depend: [Vault, Essentials]
dev-url: http://dev.bukkit.org/server-mods/payday/
commands:
   payday:
      permission: payday.admincommand
